name: "This is issues test"
description: "This is issues test"

inputs:
  filepath:
    description: Specify the filename to be created or modified
    required: true
  committer_name:
    description: This value will be used for git commit
    required: false
    default: GitHub Actions
  committer_email:
    description: This value will be used for git commit
    required: false
    default: actions@github.com

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
      shell: sh
    - name: This is issues test
      run: node $GITHUB_ACTION_PATH/app.js
      shell: sh
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        FILEPATH: ${{ inputs.filepath }}
        COMMITTER_NAME: ${{ inputs.committer_name }}
        COMMITTER_EMAIL: ${{ inputs.committer_email }}
