name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow1:
    uses: noraworld/github-actions-sandbox/.github/workflows/schedules.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
    # env:
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}

  poll-workflow-alpha:
    needs: call-workflow1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: check if all the issue are closed successfully
        run: |
          while [ "$(gh issue list | wc -l)" -ne 0 ]; do
            # echo "Some of or all of the templates have not been closed yet." >&2
            # exit 1
            sleep 15
          done
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  call-workflow2:
    needs: poll-workflow-alpha
    uses: noraworld/github-actions-sandbox/.github/workflows/issue-changer.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
    # env:
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # call-workflow-passing-data:
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
  #   with:
  #     config-path: .github/labeler.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
