name: issue_test
on:
  issues:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get year
        run: echo "YEAR=$(cut -d '-' -f1 <<< ${{ github.event.issue.title }})" >> $GITHUB_ENV

      - name: get month
        run: echo "MONTH=$(cut -d '-' -f2 <<< ${{ github.event.issue.title }})" >> $GITHUB_ENV

      - name: This is issues test
        uses: noraworld/issue-tracker@main
        with:
          filepath: _posts/${{ env.YEAR }}/${{ env.MONTH }}/${{ github.event.issue.title }}-.md
          committer_name: Kosuke Aoki
          committer_email: mail@noraworld.com
          extra_text_when_modified: "# issue からこんにちはです"
          with_date: true
          timezone: Asia/Tokyo
          time_format: h:mm a · MMM d, yyyy (ZZZZ)
