name: issue_test
on:
  issues:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get year
        run: echo "date=$(cut -d '-' -f1 <<< ${{ github.event.issue.title }})" >> $YEAR

      - name: get month
        run: echo "date=$(cut -d '-' -f2 <<< ${{ github.event.issue.title }})" >> $MONTH

      - name: This is issues test
        uses: secondnoraworld/github-actions-issues-sample@main
        with:
          filepath: _posts/$YEAR/$MONTH/${{ github.event.issue.title }}-.md
