name: issue_test
on:
  issues:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: This is issues test
        uses: secondnoraworld/github-actions-issues-sample@main
