name: Templates Creator

# on:
#   schedule:
#     - cron: '0 22 * * *'

# on:
#   workflow_dispatch:

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create issues from templates
        run: |
          ISSUE_TITLE_LIST=$(gh issue list --json title --jq .[].title)

          for issue_template in .github/ISSUE_TEMPLATE/*; do
            title=$(grep "title: " "$issue_template"               |
                    sed -e 's/^title: //g'                         |
                    sed -e "s/[\"\']//g"                           |
                    sed -e "s/\[{{DATE}}\]/$(date '+%Y-%m-%d')/g")

            if [ "$(echo "$ISSUE_TITLE_LIST" | grep -c "$title")" -ne 0 ]; then
              echo "$title already exists!" >&2
              continue
            fi

            body=$(sed -e '/^---$/,/^---$/d' "$issue_template")

            assignee=$(grep "assignees: " "$issue_template" |
                       sed -e 's/^assignees: //g'           |
                       sed -e "s/[\"\']//g")

            url=$(gh issue create           \
                    --title "$title"        \
                    --body "$body"          \
                    --assignee "$assignee")
          done
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
