name: Issue Recorder

on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get a title
        run: echo "TITLE=$(cut -d '_' -f3 <<< ${{ github.event.issue.title }})" >> $GITHUB_ENV

      - name: This is a test for Issue Recorder
        uses: noraworld/github-actions-sandbox@main
        with:
          mode: "file, issue"
          # filepath: _posts/${{ env.YEAR }}/${{ env.MONTH }}/${{ github.event.issue.title }}-.md
          # filepath: "issues/${{ github.event.issue.number }}_${{ github.event.issue.title }}.md"
          committer_name: Kosuke Aoki
          committer_email: mail@noraworld.com
          overwrite_when_modified: true
          extra_text_when_modified: "# issue からこんにちはです"
          notification_comment: このタスクの内容は [`<FILE_PATH>`](<FILE_URL>) に保存されました。
          # target_file_repo: noraworld/diary
          # target_issue_repo: noraworld/diary
          # target_issue_number: latest
          fold_threshold: infinity
          fold_summary: ここをクリックすると展開できます
          with_date: true
          timezone: Asia/Tokyo
          time_format: h:mm a · MMM d, yyyy (ZZZZ)
          with_header: "# ${{ env.TITLE }}"
          with_title: true
          # with_quote: issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
