name: Issue Recorder

on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get year
        run: echo "YEAR=$(cut -d '-' -f1 <<< ${{ github.event.issue.title }})" >> $GITHUB_ENV

      - name: get month
        run: echo "MONTH=$(cut -d '-' -f2 <<< ${{ github.event.issue.title }})" >> $GITHUB_ENV

      - name: This is a test for Issue Recorder
        uses: noraworld/github-actions-sandbox@main
        with:
          mode: "file, issue"
          # filepath: _posts/${{ env.YEAR }}/${{ env.MONTH }}/${{ github.event.issue.title }}-.md
          # filepath: "issues/${{ github.event.issue.number }}_${{ github.event.issue.title }}.md"
          committer_name: Kosuke Aoki
          committer_email: mail@noraworld.com
          extra_text_when_modified: "# issue からこんにちはです"
          notification_comment: このタスクの内容は [`<FILE_PATH>`](<FILE_URL>) に保存されました。
          # target_issue_repo: noraworld/diary
          # target_issue_number: latest
          fold_threshold: 100
          fold_summary: ここをクリックすると展開できます
          with_date: true
          timezone: Asia/Tokyo
          time_format: h:mm a · MMM d, yyyy (ZZZZ)
          # with_header: title
          with_title: true
          with_quote: issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Pile up today's to-do list on diary's issue
        run: |
          NUMBER=$(gh issue list --repo "noraworld/diary" --limit 1 | awk '{ print $1 }')
          BODY=$(gh issue view --repo "noraworld/diary" --json body --jq .body "$NUMBER")

          echo "$BODY"
          echo "[$TITLE]($URL)"

          if [ "$(echo "$BODY" | grep -c "[$TITLE]($URL)")" -eq 0 ]; then
            gh issue edit --repo "noraworld/diary" --body "$BODY
            * [x] [$TITLE]($URL)
            " "$NUMBER"
          else
            BODY=$(echo "$BODY" | sed -E 's/\* \[ \] \[$TITLE\]\($URL\)/\* \[x\] \[$TITLE\]\($URL\)/g')
            gh issue edit --repo "noraworld/diary" --body "$BODY" "$NUMBER"
          fi
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TITLE: ${{ github.event.issue.title }}
          URL: ${{ github.event.issue.html_url }}
