name: done

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: "done"
        run: |
          gh issue list | awk '{ print $1 }' | xargs -I {} gh issue edit {} --add-label 'done'
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
