name: schedule_test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: cron test
        # Note that the timezone is UTC.
        run: |
          gh issue create --title "foo with to-do" --body "$(cat GH_ISSUE_TEMPLATES.md)$(gh issue list --repo noraworld/to-do --label purchase --json title,url --template '{{"\r\n"}}{{range.}}* [ ] [{{.title}}]({{.url}}){{"\r\n"}}{{end}}')"
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
