name: Templates Closer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add done label to open issues
        run: |
          gh issue list | awk '{ print $1 }' | xargs -I {} sh -c 'sleep "$SLEEP_COUNT"; gh issue edit {} --add-label "done"'
        shell: sh
        env:
          SLEEP_COUNT: 2
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
